### ISSUE TITLE
shit coding generating a security flaw detected.

### ISSUE THREAD

**Issue by TheHowl** [miterosan/OsuOnlineTimeWatcher#3]
Looked a bit at the code, apart from thousand of style issues than aren't necessary to be pointed out, there's this.

https://github.com/miterosan/OsuOnlineTimeWatcher/blob/a2e035034a330dd488524bd2fb9648311f94e337/Java/src/irc/ircConnection.java#L37

You're lucky I don't have bad intentions.

Fix this by creating a config file where you write osu! username and IRC password in a class or something, copy the config file to a sample one and in that file remove your username and irc password. Put the name of the config file (not the sample one) into the .gitignore - get the data of the config file from ircConnection.java, and concatenate the config data to the string on line 37. Commit to github, reset your password hash (https://osu.ppy.sh/p/ircauth) and change the one in your config file.

**Comment by miterosan** [comment]
Irc password allready changed

**Comment by miterosan** [comment]
I'll fix all issues in 2 - 3 hours

**Comment by abalabahaha** [comment]
Yeh I PMed yesterday about this ._.

I might do an invasive style-focused PR soon, sorry if it offends

**Comment by miterosan** [comment]
No do it, I am happy about it ^^

**Comment by miterosan** [comment]
fixed
